(import (rnrs))

(define (triangle a b c)
  (let* ((sorted-sides (sort < (list a b c)))
         (a (car sorted-sides))
         (b (cadr sorted-sides))
         (c (caddr sorted-sides)))
    (cond ((or (= 0 a b)
               (= 0 b c)) (error 'triangle "invalid inputs"))
          ((>= c (+ a b)) (error 'triangle "invalid inputs"))
          ((= a b c) 'equilateral)
          ((or (= a b)
               (= b c)) 'isosceles)
          (else 'scalene))))
