(define/contract (find-rotation mat target)
  (-> (listof (listof exact-integer?)) (listof (listof exact-integer?)) boolean?)
  (let* ((rotate (lambda (m)
                   (apply map (compose reverse list) m)))
         (check_mat mat)
         (return #f))
    (for ((_ (range 4)))
      (if (equal? check_mat target)
          (set! return #t)
          (void))
      (set! check_mat (rotate check_mat)))
    return))
